### PR TITLE
Do not load files into memory when importing medias

### PR DESCRIPTION
**Pull request by yohanboniface**

### CODE REVIEW

**Comment by yohanboniface** [comment]
@bochecha around for a quick review?

(Or any other volunteer? :) )

**Comment by almet** [comment]
Looks good to me, don't we want tests for this as well?

**Comment by yohanboniface** [comment]
> don't we want tests for this as well?

There are already for the import itself. Or do you mean a test that would check that the file is not totally loaded in memory? Not sure how I would do that, if so ;)

**Comment by yohanboniface** [comment]
Merging, let's add specific tests if you have a point on that :)

**Pull request merged**
