### PR TITLE
Allow subpaths for packaged media

### LINKED ISSUE #753: Zipped-medias packages with subfolders can't be installed
To reproduce the problem:

```
$ python manage.py catalog remotes add Omeka "Omeka export" http://catalog.ideascube.org/omeka.yml
$ python manage.py catalog install omeka_dummy
```

The `omeka_dummy` package contains:

```
$ unzip -l storage/catalog/packages/omeka_dummy-2017-03-10
Archive:  storage/catalog/packages/omeka_dummy-2017-03-10
  Length      Date    Time    Name
---------  ---------- -----   ----
  1168607  07-20-2016 12:34   ebook/ebook_silent/feeling_smileys.jpg
    44060  08-02-2016 15:39   ebook/ebook_silent/engineer_2.jpg
   246000  08-02-2016 15:36   ebook/ebook_silent/teacher.png
   184180  12-07-2016 17:54   ebook/ebook_silent/objet_unique.png
    29557  12-07-2016 18:03   ebook/ebook_fr/c.png
   165369  08-02-2016 15:52   ebook/ebook_en/feelings_faces.png
  4288861  01-28-2016 17:10   ebook/ebook_fr/physique_de_femmes.pdf
   919477  05-27-2016 10:21   ebook/ebook_fr/ps_2011_lecorpscestaussi_animation.pdf
   846404  10-02-2013 11:10   ebook/ebook_fa/the_sociology_of_addiction.pdf
    85001  07-19-2016 12:12   ebook/ebook_ar/tuberculosis_ar.pdf
   874332  12-16-2015 14:43   ebook/ebook_refugees/universal_declaration_human_rights_farsi.pdf
 26697289  09-30-2015 14:39   ebook/ebook_refugees/visual_dictionary_for_refugees.pdf
  2718635  12-16-2015 15:16   ebook/ebook_refugees/welcome_to_germany.pdf
  1291313  07-20-2016 10:07   ebook/ebook_ar/why_baby_cry_ar.pdf
   295538  06-21-2016 11:25   ebook/ebook_de/wilkommen_arabisch.pdf
   439608  09-07-2016 10:57   ebook/ebook_fr/03_education_des_filles_1.pdf
153503125  12-08-2016 11:39   video/video_ckb/mali_eme_kurdmax_1_haci_meki_rezan_ferec.mkv
167763943  12-08-2016 11:48   video/video_ckb/mali_eme_2_kurdmax_part_2_nzar_salami_halwest.mkv
168515139  12-08-2016 12:31   video/video_ckb/mali_eme_10_p3_kurdmax_m_refiq_hana.mkv
138899045  12-08-2016 14:24   video/video_ckb/mali_eme_12_p1_kurdmax_hunarmand_brwa_taha.mkv
  4302209  07-20-2016 16:10   audio/music_ar/murder_eyez_syrian_speech.mp3
   627200  01-08-2016 12:34   audio/audio_en/words_in_the_news_walk_or_cycle_for_a_happier_commute_2.mp3
  2213510  12-17-2015 12:42   audio/music_ar/shakluka_alhasan_ahmad_lababidi.mp3
 21343007  06-12-2016 11:05   audio/music_fa/siavash_mix.mp3
  4829832  07-16-2016 23:34   audio/music_fa/valy_pashtou_attani_official_video_hd.mp3
   750298  06-29-2009 17:02   audio/audio_fr/ra_21_corrige_m1_s1.mp3
     9797  03-10-2017 10:43   manifest.yml
---------                     -------
703051336                     27 files
```

As you can see, the media files are in some subfolders.

Installing the package fails with lots of:

```
Cannot install media feeling smileys from package omeka_dummy : Some values are not valid :
 - original: * Select a valid choice. /home/mathieu/Projects/bsf/ideascube/storage/main/media/catalog/omeka_dummy/feeling_smileys.jpg is not one of the available choices.
```

### PR DESCRIPTION
**Pull request by bochecha**
Fixes #753

### CODE REVIEW

**Comment by bochecha** [comment]
We need to be careful with this. Personally, I'm not sure of the implications this might have.

@mgautierfr please review carefully.

Of course it's missing tests, but for now I'd like us to think hard about where this might take us.

**Comment by mgautierfr** [comment]
This looks good (beside the missing tests).

The other solutions would have been to extra the media package differently, flatting all the files inside to remove subdirectory. This over complicate the things.

However, it points me a potential security issues if the media package (zip) contains a symlink to a file somewhere else on the system. This would allow an attacker to get a file content he should not get.
But this is not related to this PR, this is an already existing problem with the actual code.
This is mitigated by the fact we handle the packages we provide. But we have to handle this point.

**Comment by bochecha** [comment]
> However, it points me a potential security issues if the media package (zip) contains a symlink to a file somewhere else on the system. This would allow an attacker to get a file content he should not get.
But this is not related to this PR, this is an already existing problem with the actual code.
This is mitigated by the fact we handle the packages we provide. But we have to handle this point.

Good point!

We should just disallow symlinks in media packages IMHO. (i.e if a media package installs a symlink, treat it as an error, and don't install this specific media)

**Comment by bochecha** [comment]
I forgot to leave a note here, but I added some tests (by modifying the existing zipped media test package so it contains a subfolder)

**Comment by mgautierfr** [comment]
Seems good to me.

**Pull request merged**
