### PR TITLE
CommaSeparatedCharField is now checkboxes by default

### PR DESCRIPTION
**Pull request by vinyll**
Replacing multiple select combo box by a list of checkboxes

### CODE REVIEW

**Comment by bochecha** [comment]
Why remove the `blank=True` for all these fields?

**Comment by vinyll** [comment]
@bochecha: We switched from a multiple combobox to a list of checkboxes.
we do not what something like this:

- [ ] ----------

That item appears when the form field is `required = True`, that is generated by the `blank=True`.
What we actually want is a nullable field.

**Comment by vinyll** [comment]
Closed by mistake

**Comment by bochecha** [comment]
> That item appears when the form field is required = True, that is generated by the blank=True.
What we actually want is a nullable field.

nullable or blankable? Django has both `null=True` and `blank=True`, so I'm not sure I follow.

**Comment by vinyll** [comment]
@bochecha We only want to impact the form validation here. No change for the database so no change for `null=xxx`. Only [changing to `blank=False`](https://docs.djangoproject.com/en/1.10/ref/models/fields/#blank)

**Comment by bochecha** [comment]
> We only want to impact the form validation here.

What I'm asking since the first comment is why.

I'm asking because I genuinely don't understand why.

I know what `blank=` does, what I don't get is why it was necessary to change its value, in functional terms.

**Comment by vinyll** [comment]
I guess a picture will speak better than I do ;)

With `blank=True`:
screen shot 2016-10-06 at 7 34 40 pm

After removing the blank argument:
screen shot 2016-10-06 at 7 30 18 pm

We want this result because it makes no sense to have the `[ ] ------------` is a checkbox list.

**Comment by yohanboniface** [comment]
In other words: `blank=True` makes Django adding a blank choice in our choices, which we don't want.

**Comment by yohanboniface** [comment]
> It seems to me we're (or Django is) confusing two unrelated things here: form validation and widget presentation.

I think that this is (sadly) the case. But we may have a better way to deal with the situation, and that was actually the first code of @vinyll that I then asked to change.

First thing: I thought `blank` argument was strictly a shortcut from the model field to control the `required` argument on the form field when automatically created by Django, but it's not, it's also used by the Model field `validate`: https://github.com/django/django/blob/master/django/db/models/fields/__init__.py#L582

Then, Django `does` add to the model field choices an empty choice when `blank=True`: https://github.com/django/django/blob/master/django/db/models/fields/__init__.py#L788 

This is only done if the `get_choices` receive `include_blank=True`, which is the case when `blank=True`: https://github.com/django/django/blob/master/django/db/models/fields/__init__.py#L853

So I'm (after years of using Django) still confused by the behaviour of `null/blank/required` :/

Anyway, I now sort of think that changing `blank` value here is not what we want to do, given it also affects the Model field behaviour. And then the initial option of @vinyll may be better: also overriding `get_choices` in our `CommaSeparatedField` to force `include_blank=False`.

**Comment by bochecha** [comment]
> So I'm (after years of using Django) still confused by the behaviour of null/blank/required :/

great, you're confirming what I was feeling: that years from now I still will be confused by that. :laughing: 

> And then the initial option of @vinyll may be better: also overriding get_choices in our CommaSeparatedField to force include_blank=False.

Yes, this.

**Comment by yohanboniface** [comment]
This certainly means rebasing and resetting the migration after https://github.com/ideascube/ideascube/pull/539

**Comment by vinyll** [comment]
I've updated the PR considering your feedbacks and digging a little further.
It consistently simplifies the changes.

**Comment by bochecha** [comment]
Oops, I approved before seeing the tests had failed.

Can you rebase on the latest master, and fix the unit tests before we merge?

**Comment by vinyll** [comment]
Yup, that's in the pipe ;)

**Pull request merged**
