### PR TITLE
Fix for idb_jor_hostcommunity user form fields.

### PR DESCRIPTION
**Pull request by letompouce**
Narjis says the hostcommunity conf should import its USER_FORM_FIELDS
from alhashmi instead of azraq's ones.

### CODE REVIEW

**Comment by bochecha** [comment]
> Narjis says the hostcommunity conf should import its USER_FORM_FIELDS
from alhashmi instead of azraq's ones.

But your change imports **everything** from the alhashmi config.

Right now, the alashmi config imports the azraq one and just overrides the `USER_FORM_FIELDS` so that achieves your goal.

However we have **5** levels of configuration inheritance here: hostcommunity inherits from alashmi which inherits from azraq which inherits from idb which inherits from base.

This looks like a recipe for trouble if we're not careful.

**Comment by letompouce** [comment]
cc @Narjis89

**Comment by letompouce** [comment]
Our options so far:
* Repeat the `USER_FORM_FIELDS` tweak in both `idb_jor_alhashmi.py` & `idb_jor_hostcommunity.py`. Redundant code.
* Create a generic `idb_jor.py` file to import in all the others. This only adds another layer of inclusion. Not to talk about the future JOR projects and their potential willing to tweak `USER_FORM_FIELDS` or something else.
* Live with it and be careful.

I'd tend to apply the third option.

But I wanna check about the `ENTRY_ACTIVITY_CHOICE` micmac as well before we merge...

**Comment by Narjis89** [comment]
I'm with choice number 3 also 
And for the  ENTRY_ACTIVITY_CHOICE no one has any complain about it , we can keep it as it

**Comment by bochecha** [comment]
Alright, thanks for thinking about this, let's go with it. 😃

**Pull request merged**
